### ISSUE TITLE
Project is being sunset 

### ISSUE THREAD

**Issue by MikeGoldsmith** [honeycombio/heroku-honeycomb-drain#10]
See [OSS lifecycle and practices](https://github.com/honeycombio/home/blob/main/honeycomb-oss-lifecycle-and-practices.md)

This project has outlived its useful lifespan, and will be archived in the future. You can replace usage of this drain with the [syslog drain](https://devcenter.heroku.com/articles/log-drains#syslog-drains) and send to an OpenTelemetry Collector using the [syslog receiver](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/syslogreceiver).

If you are actively using `heroku-honeycomb-drain`, please comment on this issue with your use case.

**Comment by vreynolds** [comment]
Project is archived
