### ISSUE TITLE
Tracing from router to app

### ISSUE THREAD

**Issue by s5no5t** [honeycombio/heroku-honeycomb-drain#2]
There is currently no way to combine routing logs from Heroku with events from the apps running on Heroku. If it were, events from the Heroku router could be combined with app events to traces in Honeycomb.

The `express` instrumentation from Beeline (and others probably, too) uses the `X-Request-ID` header value as the trace id by default. The same value is logged as `request_id` by the Heroku router. If I understand correctly, `request_id` would have to be used for `trace.trace_id`.

**Comment by JamieDanielson** [comment]
This project is being sunset; please review issue #10
