### ISSUE TITLE
docs request: can this run on Heroku for free?

### ISSUE THREAD

**Issue by jessitron** [honeycombio/heroku-honeycomb-drain#3]
I tried the "deploy to heroku" button, entered all the things, and then it worked on starting up and at the very end told me "oh no, I can't start this because you haven't entered a credit card."
I am guessing that this configures a particular level of dyno?

Could you document that with the button?

As a bonus, it'd be lovely if there were instructions for deploying it manually in a free dyno. It'd only need to run a few hours a week for my toy app. I'm sad to have to pay for it, but I don't want to figure out how to build and deploy a Go app tonight.

**Comment by JamieDanielson** [comment]
This project is being sunset; please review issue #10
